services:
  postgres_hotels_db:
    container_name: postgres-hotels
    image: postgres:18.1-alpine
    restart: always
    environment:
      POSTGRES_DB: hotels
      POSTGRES_USER: spring
      POSTGRES_PASSWORD: spring
    ports:
      - "5050:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  postgres_hotels_test_db:
    container_name: postgres-hotels-test
    image: postgres:18.1-alpine
    restart: always
    environment:
      POSTGRES_DB: hotels_test
      POSTGRES_USER: spring
      POSTGRES_PASSWORD: spring
    ports:
      - "5051:5432"
    volumes:
      - test-db-data:/var/lib/postgresql/data

volumes:
  db-data:
  test-db-data: