# Create tables automatically
spring.jpa.hibernate.ddl-auto=none
# Ensure schema.sql + data.sql always execute
spring.sql.init.mode=always
# Disable open session in view
spring.jpa.open-in-view=false
# Ensure schema/data SQL run after JPA initialization
spring.jpa.defer-datasource-initialization=true
# Show SQL in console
logging.level.org.hibernate.SQL=DEBUG