# PRODUCTION PROFILE (PostgreSQL + JPA)

# Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=demo_orm

spring.jpa.defer-datasource-initialization=true

# PostgreSQL database
spring.datasource.url=jdbc:postgresql:pro3_db
spring.datasource.username=postgres
spring.datasource.password=Student_1234
#spring.datasource.driver-class-name=org.postgresql.Driver

# Do NOT load schema.sql or data.sql in prod
spring.sql.init.mode=always