# JDBC PROFILE (schema.sql + data.sql)

# H2 Database (In-Memory)
spring.datasource.url=jdbc:h2:mem:hotelsdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=hotelDatabase
spring.datasource.password=

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Run schema.sql + data.sql ALWAYS
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

