# PostgreSQL Configuration (PROD)
spring.datasource.url=jdbc:postgresql://localhost:5432/pro3_db
spring.datasource.username=postgres
spring.datasource.password=Student_1234
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA / HIBERNATE
# do NOT recreate tables
spring.jpa.hibernate.ddl-auto=none
# Show SQL in console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Disable Open Session in View
spring.jpa.open-in-view=false
# SQL initialization behavior
spring.sql.init.mode=never