# Thymeleaf dev settings
spring.thymeleaf.cache=false

# Logging (global)
logging.level.root=INFO

logging.level.be.kdg.prog3=DEBUG

# server.port=8080

spring.messages.basename=messages
#spring.web.locale-resolver=fixed
#spring.web.locale=en
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false