# (H2 + Hibernate)
# Do NOT let Hibernate create or modify tables automatically
spring.jpa.hibernate.ddl-auto=none
# Show generated SQL queries in the console (debugging & learning)
spring.jpa.show-sql=true
# Format SQL nicely so it is readable in logs
spring.jpa.properties.hibernate.format_sql=true
# H2 Database (in memory)
spring.datasource.url=jdbc:h2:mem:hotelsdb

# H2 JDBC driver
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=hotelDatabase
spring.datasource.password=hotel123

# Enable H2 web console for inspecting data
spring.h2.console.enabled=true
# Accessible at: http://localhost:8080/h2-console
spring.h2.console.path=/h2-console
# Always run schema.sql and data.sql if present
spring.sql.init.mode=always