# DEV PROFILE (H2 + JPA)

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Database (in memory)
spring.datasource.url=jdbc:h2:mem:hotelsdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=hotelDatabase
spring.datasource.password=hotel123

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Do NOT execute schema.sql or data.sql
spring.sql.init.mode=always