# Thymeleaf dev settings
spring.thymeleaf.cache=false

# Logging (global)
logging.level.root=INFO

logging.level.be.kdg.prog3=DEBUG

# server.port=8080

spring.messages.basename=messages
#spring.web.locale-resolver=fixed
#spring.web.locale=en
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false

# General
spring.application.name=Hotels
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
# inmemory for DataFactory / jdbc for database
spring.profiles.active=jdbc

# H2 in-memory database
spring.datasource.url=jdbc:h2:mem:hotelsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=hotelDatabase
spring.datasource.password=hotel123