# In-memory profile uses DataFactory instead of SQL scripts
spring.sql.init.mode=never
logging.level.be.kdg.prog3=DEBUG
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false