INSERT INTO hotels (id, name, opened_on, stars, has_spa, image_url)
VALUES ('plaza-athenee-paris', 'Hotel Plaza Athénée, Paris', '1913-05-20', 5, true, '/images/hotels/plaza_athene.jpg'),
       ('langham-london', 'The Langham, London', '1865-01-01', 5, false, '/images/hotels/langham.jpg'),
       ('radisson-stockholm', 'Radisson Blu Strand, Stockholm', '1912-04-15', 4, false,
        '/images/hotels/radisson_blu_strand.jpg'),
       ('radisson-antwerp', 'Radisson Blu Astrid Hotel, Antwerp', '1998-06-15', 4, true,
        '/images/hotels/radisson_blu_antwerp.jpg'),
       ('amigo-brussels', 'Hotel Amigo, Brussels', '1957-09-01', 5, true, '/images/hotels/amigo.jpg'),
       ('hilton-old-town', 'Hilton Old Town, Antwerp', '1957-09-01', 5, true, '/images/hotels/hilton.jpg'),
       ('c-hotels-slit', 'C-Hotels Silt, Middelkerke', '2024-03-22', 4, true, '/images/hotels/silt.jpg'),
       ('van-der-valk', 'Van der Valk Hotel, Ghent', '2021-04-01', 4, true, '/images/hotels/van_der.jpg'),
       ('pan-pacific', 'Pan Pacific, London', '2021-09-01', 5, true, '/images/hotels/pan_pacific.jpg');

INSERT INTO rooms (number, type, price_per_night, sea_view, photo_url)
VALUES (101, 'SINGLE', 150.0, false, '/images/rooms/plaza_athene_single.jpg'),
       (102, 'DOUBLE', 250.0, true, '/images/rooms/plaza_athene_double.jpg'),
       (201, 'SUITE', 500.0, true, '/images/rooms/plaza_athene_suite.jpg'),
       (202, 'DOUBLE', 220.0, false, '/images/rooms/langham_double.jpg'),
       (301, 'SINGLE', 180.0, true, '/images/rooms/langham_single.jpg'),
       (302, 'SUITE', 550.0, false, '/images/rooms/radisson_blu_strand_suite.jpg'),
       (401, 'SUITE', 450.0, true, '/images/rooms/langham_suite.jpg'),
       (402, 'SINGLE', 140.0, false, '/images/rooms/radisson_blu_strand_single.jpg'),
       (403, 'DOUBLE', 350.0, false, '/images/rooms/radisson_blu_strand_double.jpg'),
       (501, 'DOUBLE', 210.0, true, '/images/rooms/radisson_blu_antwerp_double.jpg'),
       (502, 'SUITE', 480.0, false, '/images/rooms/radisson_blu_antwerp_suite.jpg'),
       (503, 'SINGLE', 130.0, true, '/images/rooms/radisson_blu_antwerp_single.jpg'),
       (601, 'SINGLE', 160.0, false, '/images/rooms/amigo_single.jpg'),
       (602, 'DOUBLE', 240.0, true, '/images/rooms/amigo_double.jpg'),
       (603, 'SUITE', 520.0, true, '/images/rooms/amigo_suite.jpg'),
       (450, 'SUITE', 540.0, false, '/images/rooms/hilton_suite.jpg'),
       (480, 'DOUBLE', 260.0, false, '/images/rooms/hilton_double.jpg'),
       (490, 'SINGLE', 140.0, false, '/images/rooms/hilton_single.jpg'),
       (533, 'SUITE', 590.0, true, '/images/rooms/silt_suite.jpg'),
       (563, 'DOUBLE', 270.0, true, '/images/rooms/silt_double.jpg'),
       (579, 'SINGLE', 160.0, true, '/images/rooms/silt_single.jpg'),
       (703, 'SUITE', 420.0, true, '/images/rooms/van_der_suite.jpg'),
       (705, 'DOUBLE', 200.0, true, '/images/rooms/van_der_double.jpg'),
       (709, 'SINGLE', 110.0, true, '/images/rooms/van_der_single.jpg'),
       (811, 'SUITE', 565.0, false, '/images/rooms/pan_pacific_suite.jpg'),
       (839, 'DOUBLE', 300.0, false, '/images/rooms/pan_pacific_double.jpg'),
       (857, 'SINGLE', 220.0, false, '/images/rooms/pan_pacific_suite.jpg');

INSERT INTO guests (full_name, dob, email, vip, avatar_url)
VALUES ('Billie Wilson', '1990-04-10', 'billie.wilson@example.com', true, '/images/guests/billie_wilson.jpg'),
       ('Liam Johnson', '1985-12-03', 'liam.johnson@example.com', false, '/images/guests/liam_johnson.jpg'),
       ('Sophia Martinez', '1992-09-18', 'sophia.martinez@example.com', true, '/images/guests/sophia_martinez.jpg'),
       ('Ahanyna Saha', '2002-11-28', 'ahanyna.saha@gmail.com', true, '/images/guests/ahanyna_saha.jpg'),
       ('Olivia Garcia', '1995-02-08', 'olivia.garcia@example.com', true, '/images/guests/olivia_garcia.jpg'),
       ('Ethan Brown', '1991-06-15', 'ethan.brown@example.com', false, '/images/guests/ethan_brown.jpg'),
       ('Mia Chen', '1997-03-22', 'mia.chen@example.com', true, '/images/guests/mia_chen.jpg'),
       ('Alexander Rossi', '1989-11-09', 'alex.rossi@example.com', false, '/images/guests/alexander_rossi.jpg'),
       ('Marrison Harri', '2001-06-12', 'harri@example.com', true, '/images/guests/marrison_harri.jpg'),
       ('Emma Janssens', '1995-04-10', 'emma.janssens@example.com', false, '/images/guests/emma_janssens.jpg'),
       ('Lucas Peeters', '1988-11-21', 'lucas.peeters@example.com', true, '/images/guests/lucas_peeters.jpg'),
       ('Kate Claes', '1992-07-15', 'kate.claes@example.com', false, '/images/guests/kate_claes.jpg'),
       ('Noah Smith', '1988-07-25', 'noah.smith@example.com', false, '/images/guests/noah_smith.jpg');